# Generated by Django 5.0.3 on 2026-01-16 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='level',
        ),
        migrations.AddField(
            model_name='language',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='language_icons/'),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.language')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
